/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2022 Rockchip Electronics Co., Ltd.
 */

#ifndef _HAL_CONF_H_
#define _HAL_CONF_H_

/* CPU config */
#define SOC_RK3506
#define HAL_AP_CORE

/* System timer designation (RK TIMER) */
#define SYS_TIMER TIMER5

/* HAL Driver Config */
#define HAL_ACDCDIG_DSM_MODULE_ENABLED
#define HAL_ACODEC_MODULE_ENABLED
#define HAL_CPU_TOPOLOGY_MODULE_ENABLED
#define HAL_CRU_MODULE_ENABLED
#define HAL_CRYPTO_MODULE_ENABLED
#define HAL_DCACHE_MODULE_ENABLED
#define HAL_DSMC_HOST_MODULE_ENABLED
#define HAL_DSMC_SLAVE_MODULE_ENABLED
#define HAL_DW_MIPI_DSI_MODULE_ENABLED
#define HAL_FLEXBUS_ADC_MODULE_ENABLED
#define HAL_FLEXBUS_DAC_MODULE_ENABLED
#define HAL_FLEXBUS_SPI_MODULE_ENABLED
#define HAL_FLEXBUS_MODULE_ENABLED
#define HAL_FSPI_MODULE_ENABLED
#define HAL_INNO_MIPI_DPHY_MODULE_ENABLED
#define HAL_IRQ_HANDLER_MODULE_ENABLED
#define HAL_GIC_MODULE_ENABLED
#define HAL_GPIO_MODULE_ENABLED
#define HAL_MBOX_MODULE_ENABLED
#define HAL_NPOR_MODULE_ENABLED
#define HAL_PINCTRL_MODULE_ENABLED
#define HAL_PL330_MODULE_ENABLED
#define HAL_PWM_MODULE_ENABLED
#define HAL_SAI_MODULE_ENABLED
#define HAL_SNOR_MODULE_ENABLED
#define HAL_SPDIFRX_MODULE_ENABLED
#define HAL_SPDIFTX_MODULE_ENABLED
#define HAL_TIMER_MODULE_ENABLED
#define HAL_TRNG_MODULE_ENABLED
#define HAL_UART_MODULE_ENABLED

#ifdef HAL_GIC_MODULE_ENABLED
#define HAL_GIC_AMP_FEATURE_ENABLED
#define HAL_GIC_PREEMPT_FEATURE_ENABLED
#define HAL_GIC_WAIT_LINUX_INIT_ENABLED
#endif

#ifdef HAL_GPIO_MODULE_ENABLED
#define HAL_GPIO_IRQ_DISPATCH_FEATURE_ENABLED
#define HAL_GPIO_VIRTUAL_MODEL_FEATURE_ENABLED
#endif

/* HAL_DBG SUB CONFIG */

#define HAL_DBG_ON
#ifdef HAL_DBG_ON
#define HAL_DBG_USING_HAL_PRINTF
#define HAL_DBG_ON
#define HAL_DBG_INFO_ON
#define HAL_DBG_WRN_ON
#define HAL_DBG_ERR_ON
#endif  /* End of HAL_DBG_ON */

#endif  /* End of _HAL_CONF_H_ */
