# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2024 Rockchip Electronics Co., Ltd.

PROJECT		:= RV1103B
SOC		:= RV1103B
CPU		:= -march=rv32imac -mabi=ilp32

include ../../common/GCC/riscv.mk
